-- 112 — the whole return, field by field, and where each 2025 answer comes from
--
-- `094`–`097` put Parts VIII and IX on the return's own lines and `110`–`111`
-- did Part X. Those are the three financial statements and they are **a third
-- of the document**: the 2024 filing is thirty-six pages, and the rest of it
-- is a mission statement, four checklists of Yes and No, a governance section,
-- a signature block and seven schedules. A "2025 Form 990" that prints three
-- statements and nothing else is not a return; it is three schedules with a
-- cover.
--
-- So this is the other two thirds, transcribed from the filed 2024 return —
-- **every field, with its 2024 answer as printed** — and beside each one,
-- where the 2025 answer comes from. That last column is the whole design,
-- because there are only four honest answers and they lead to different work:
--
--   `record`   the record answers it, and `source` says which view. Nothing
--              is recalled and nothing is computed twice.
--   `field`    the form defines it as another line of itself — *must equal
--              Part VIII, column (A), line 12*. A reference, not a
--              derivation.
--   `carried`  a fact about the organisation that 2025 does not move: the
--              EIN, the state of domicile, whether there is a written
--              conflict of interest policy. **Carried is not measured**, and
--              the rendered return says so on every one, because a carried
--              answer somebody has to confirm and a read one they do not are
--              different facts and printing them alike is how a return gets
--              signed over a stale answer.
--   `ask`      nobody has answered it for 2025 and nothing on the record can.
--              It prints as the question rather than blank and rather than
--              the 2024 answer — *a blank is unanswered, and unanswered is a
--              value*, which this file has held since the intake was built.
--
-- The 2024 column is a **source document**, the way `form_990_prior_year`
-- already is for Parts VIII and IX: read off the filing that has been in
-- `docs/source-documents/tax-filings/` since the foundation was loaded, not
-- recalled. *Figures in a document for somebody else get read from the
-- record, not recalled* — applied to somebody else's document.

CREATE TABLE form_990_field (
  field_id   text PRIMARY KEY,
  part       text NOT NULL,
  seq        integer NOT NULL,
  line_no    text NOT NULL DEFAULT '',
  label      text NOT NULL,
  kind       text NOT NULL
             CHECK (kind IN ('MONEY','COUNT','PERCENT','YESNO','TEXT',
                             'CHECKBOX','HEADING')),
  answer     text NOT NULL
             CHECK (answer IN ('record','field','carried','ask')),
  source     text NOT NULL DEFAULT '',
  note       text NOT NULL DEFAULT '',
  -- A field answered from the record or by reference has to say from what.
  -- A source with nothing in it is the citation-with-no-document shape, and
  -- this register is large enough that one would never be noticed by eye.
  CONSTRAINT a_read_field_names_its_source
    CHECK (answer NOT IN ('record','field') OR length(btrim(source)) > 0),
  -- And an ask has to say what is being asked for, or it is "cannot be
  -- answered" with no way to act on it — the dead end this file keeps finding.
  CONSTRAINT an_ask_says_what_it_wants
    CHECK (answer <> 'ask' OR length(btrim(source)) >= 12)
);

COMMENT ON TABLE form_990_field IS
  'Every field of Form 990 outside Parts VIII, IX and X, and where the '
  'answer comes from. Four answers — read, referenced, carried, asked — '
  'because a carried answer and a measured one are different facts and a '
  'return that prints them alike gets signed over a stale one.';

CREATE TABLE form_990_prior_field (
  period    text NOT NULL REFERENCES fiscal_period(period),
  field_id  text NOT NULL REFERENCES form_990_field(field_id),
  value     text NOT NULL,
  PRIMARY KEY (period, field_id)
);

COMMENT ON TABLE form_990_prior_field IS
  'The filed return, as printed. A source document transcribed, not a '
  'constant in a script — the rule form_990_prior_year already follows for '
  'Parts VIII and IX.';

INSERT INTO form_990_field
  (field_id, part, seq, line_no, label, kind, answer, source, note)
VALUES
  ('H_PERIOD', 'HEAD', 10, 'A', 'For the calendar year, or tax year beginning and ending', 'TEXT', 'record', 'fn:tax_year', ''),
  ('H_BOX', 'HEAD', 20, 'B', 'Check if applicable', 'CHECKBOX', 'carried', '', 'None of address change, name change, initial, final, amended or application pending was checked.'),
  ('H_NAME', 'HEAD', 30, 'C', 'Name of organization', 'TEXT', 'carried', '', ''),
  ('H_DBA', 'HEAD', 40, 'C', 'Doing business as', 'TEXT', 'carried', '', ''),
  ('H_STREET', 'HEAD', 50, 'C', 'Number and street', 'TEXT', 'carried', '', ''),
  ('H_CITY', 'HEAD', 60, 'C', 'City, state and ZIP', 'TEXT', 'carried', '', ''),
  ('H_EIN', 'HEAD', 70, 'D', 'Employer identification number', 'TEXT', 'carried', '', ''),
  ('H_PHONE', 'HEAD', 80, 'E', 'Telephone number', 'TEXT', 'carried', '', ''),
  ('H_GROSS', 'HEAD', 90, 'G', 'Gross receipts', 'MONEY', 'field', 'add:field:P1_12,ix:8b:total', 'Total revenue plus the fundraising direct expenses Part VIII nets against line 8a. The 2024 return is 7,546,159 + 139,739 = 7,685,898, which is how this reference was checked rather than assumed.'),
  ('H_OFFICER', 'HEAD', 100, 'F', 'Name and address of principal officer', 'TEXT', 'carried', '', ''),
  ('H_STATUS', 'HEAD', 110, 'I', 'Tax-exempt status', 'CHECKBOX', 'carried', '', ''),
  ('H_WEB', 'HEAD', 120, 'J', 'Website', 'TEXT', 'carried', '', ''),
  ('H_GROUPA', 'HEAD', 130, 'H(a)', 'Is this a group return for subordinates?', 'YESNO', 'carried', '', ''),
  ('H_GROUPB', 'HEAD', 140, 'H(b)', 'Are all subordinates included?', 'YESNO', 'carried', '', ''),
  ('H_GROUPC', 'HEAD', 150, 'H(c)', 'Group exemption number', 'TEXT', 'carried', '', ''),
  ('H_FORM', 'HEAD', 160, 'K', 'Form of organization', 'CHECKBOX', 'carried', '', ''),
  ('H_FORMED', 'HEAD', 170, 'L', 'Year of formation', 'COUNT', 'carried', '', ''),
  ('H_DOMICILE', 'HEAD', 180, 'M', 'State of legal domicile', 'TEXT', 'carried', '', ''),
  ('P1_1', 'I', 190, '1', 'Briefly describe the organization''s mission or most significant activities', 'TEXT', 'carried', '', 'The 2024 return prints this twice with a transcription error (PRMOTE, RESORUCES) and the second half repeating the first. Carried as the sentence rather than as the duplication, and the preparer confirms it.'),
  ('P1_2', 'I', 200, '2', 'Check this box if the organization discontinued its operations or disposed of more than 25% of its net assets', 'CHECKBOX', 'carried', '', ''),
  ('P1_3', 'I', 210, '3', 'Number of voting members of the governing body', 'COUNT', 'field', 'field:P6_1A', ''),
  ('P1_4', 'I', 220, '4', 'Number of independent voting members of the governing body', 'COUNT', 'field', 'field:P6_1B', ''),
  ('P1_5', 'I', 230, '5', 'Total number of individuals employed in the calendar year', 'COUNT', 'record', 'fn:employees', 'The payroll register''s own count of people paid in the year.'),
  ('P1_6', 'I', 240, '6', 'Total number of volunteers', 'COUNT', 'ask', 'a count of volunteers, which nothing on this record holds', 'The 2024 return reported nought, which is a figure somebody chose rather than one the books produce.'),
  ('P1_7A', 'I', 250, '7a', 'Total unrelated business revenue from Part VIII, column (C), line 12', 'MONEY', 'ask', 'which revenue is unrelated business income — a judgment per stream', 'Nothing on the record classifies revenue as related or unrelated. The 2024 return reported nought here and 227,890 of net unrelated business income on Schedule A Part II line 9, which are two different answers to neighbouring questions and is why this one is asked rather than carried.'),
  ('P1_7B', 'I', 260, '7b', 'Net unrelated business taxable income from Form 990-T, Part I, line 11', 'MONEY', 'ask', 'the Form 990-T, if one is filed for this year', ''),
  ('P1_8', 'I', 270, '8', 'Contributions and grants (Part VIII, line 1h)', 'MONEY', 'field', 'viii:V1', ''),
  ('P1_9', 'I', 280, '9', 'Program service revenue (Part VIII, line 2g)', 'MONEY', 'field', 'viii:V2', ''),
  ('P1_10', 'I', 290, '10', 'Investment income (Part VIII, column (A), lines 3, 4 and 7d)', 'MONEY', 'field', 'viii:V3', ''),
  ('P1_11', 'I', 300, '11', 'Other revenue (Part VIII, column (A), lines 5, 6d, 8c, 9c, 10c and 11e)', 'MONEY', 'field', 'add:viii:V5,viii:V6,viii:V8,viii:V10,viii:V11,neg:ix:8b:total', 'Line 8c is the fundraising event net of its own direct expenses, so 8b comes off here rather than in Part IX.'),
  ('P1_12', 'I', 310, '12', 'Total revenue — add lines 8 through 11 (must equal Part VIII, column (A), line 12)', 'MONEY', 'field', 'add:field:P1_8,field:P1_9,field:P1_10,field:P1_11', ''),
  ('P1_13', 'I', 320, '13', 'Grants and similar amounts paid (Part IX, column (A), lines 1–3)', 'MONEY', 'field', 'ixsum:1,2,3:total', ''),
  ('P1_14', 'I', 330, '14', 'Benefits paid to or for members (Part IX, column (A), line 4)', 'MONEY', 'field', 'ix:4:total', ''),
  ('P1_15', 'I', 340, '15', 'Salaries, other compensation, employee benefits (Part IX, column (A), lines 5–10)', 'MONEY', 'field', 'ixsum:5,6,7,8,9,10:total', ''),
  ('P1_16A', 'I', 350, '16a', 'Professional fundraising fees (Part IX, column (A), line 11e)', 'MONEY', 'field', 'ix:11e:total', ''),
  ('P1_16B', 'I', 360, '16b', 'Total fundraising expenses (Part IX, column (D), line 25)', 'MONEY', 'field', 'ixtotal:fundraising', ''),
  ('P1_17', 'I', 370, '17', 'Other expenses (Part IX, column (A), lines 11a–11d, 11f–24e)', 'MONEY', 'field', 'sub:field:P1_18,add:field:P1_13,field:P1_14,field:P1_15,field:P1_16A', ''),
  ('P1_18', 'I', 380, '18', 'Total expenses. Add lines 13–17 (must equal Part IX, column (A), line 25)', 'MONEY', 'field', 'ixtotal:total', ''),
  ('P1_19', 'I', 390, '19', 'Revenue less expenses. Subtract line 18 from line 12', 'MONEY', 'field', 'sub:field:P1_12,field:P1_18', ''),
  ('P1_20', 'I', 400, '20', 'Total assets (Part X, line 16)', 'MONEY', 'field', 'x16', ''),
  ('P1_21', 'I', 410, '21', 'Total liabilities (Part X, line 26)', 'MONEY', 'field', 'x26', ''),
  ('P1_22', 'I', 420, '22', 'Net assets or fund balances. Subtract line 21 from line 20', 'MONEY', 'field', 'sub:field:P1_20,field:P1_21', ''),
  ('P2_SIG', 'II', 430, '', 'Signature of officer', 'TEXT', 'ask', 'the signature of an officer, which is not something a system supplies', ''),
  ('P2_PREP', 'II', 440, '', 'Paid preparer''s firm', 'TEXT', 'carried', '', ''),
  ('P2_DISCUSS', 'II', 450, '', 'May the IRS discuss this return with the preparer shown above?', 'YESNO', 'carried', '', ''),
  ('P3_1', 'III', 460, '1', 'Briefly describe the organization''s mission', 'TEXT', 'field', 'field:P1_1', ''),
  ('P3_2', 'III', 470, '2', 'Did the organization undertake any significant program services during the year which were not listed on the prior Form 990 or 990-EZ?', 'YESNO', 'carried', '', ''),
  ('P3_3', 'III', 480, '3', 'Did the organization cease conducting, or make significant changes in how it conducts, any program services?', 'YESNO', 'carried', '', ''),
  ('P3_4A_EXP', 'III', 490, '4a', 'Program service — expenses', 'MONEY', 'record', 'ixtotal:program', ''),
  ('P3_4A_GRANT', 'III', 500, '4a', 'Program service — including grants of', 'MONEY', 'field', 'ixsum:1,2,3:program', ''),
  ('P3_4A_REV', 'III', 510, '4a', 'Program service — revenue', 'MONEY', 'ask', 'the revenue attributable to the programme, which the record does not split by programme', 'The 2024 return reported 634,307 against a single programme. Revenue here is by programme and the ledger''s income is by grant, which are not the same cut.'),
  ('P3_4A_DESC', 'III', 520, '4a', 'Program service — description', 'TEXT', 'carried', '', ''),
  ('P3_4E', 'III', 530, '4e', 'Total program service expenses', 'MONEY', 'field', 'ixtotal:program', ''),
  ('P11_1', 'XI', 540, '1', 'Total revenue (must equal Part VIII, column (A), line 12)', 'MONEY', 'field', 'field:P1_12', ''),
  ('P11_2', 'XI', 550, '2', 'Total expenses (must equal Part IX, column (A), line 25)', 'MONEY', 'field', 'field:P1_18', ''),
  ('P11_3', 'XI', 560, '3', 'Revenue less expenses. Subtract line 2 from line 1', 'MONEY', 'field', 'field:P1_19', ''),
  ('P11_4', 'XI', 570, '4', 'Net assets or fund balances at beginning of year (must equal Part X, line 32, column (A))', 'MONEY', 'record', 'fn:net_assets_boy', 'The prior return''s own end-of-year figure, which is what the column means.'),
  ('P11_5', 'XI', 580, '5', 'Net unrealized gains (losses) on investments', 'MONEY', 'carried', '', ''),
  ('P11_6', 'XI', 590, '6', 'Donated services and use of facilities', 'MONEY', 'carried', '', ''),
  ('P11_7', 'XI', 600, '7', 'Investment expenses', 'MONEY', 'carried', '', ''),
  ('P11_8', 'XI', 610, '8', 'Prior period adjustments', 'MONEY', 'carried', '', ''),
  ('P11_9', 'XI', 620, '9', 'Other changes in net assets or fund balances (explain in Schedule O)', 'MONEY', 'field', 'sub:field:P11_10,add:field:P11_3,field:P11_4', 'Whatever line 10 needs in order to be Part X line 32 — and the return prints the figure rather than forcing it, so a difference the record cannot explain shows as one. The 2024 return carried -50,000 here.'),
  ('P11_10', 'XI', 630, '10', 'Net assets or fund balances at end of year. Combine lines 3 through 9 (must equal Part X, line 32, column (B))', 'MONEY', 'field', 'x32', ''),
  ('P12_1', 'XII', 640, '1', 'Accounting method used to prepare the Form 990', 'CHECKBOX', 'carried', '', ''),
  ('P12_2A', 'XII', 650, '2a', 'Were the organization''s financial statements compiled or reviewed by an independent accountant?', 'YESNO', 'carried', '', ''),
  ('P12_2B', 'XII', 660, '2b', 'Were the organization''s financial statements audited by an independent accountant?', 'YESNO', 'carried', '', 'Audited on a separate basis in 2024.'),
  ('P12_2C', 'XII', 670, '2c', 'Does the organization have a committee that assumes responsibility for oversight of the audit?', 'YESNO', 'carried', '', ''),
  ('P12_3A', 'XII', 680, '3a', 'As a result of a federal award, was the organization required to undergo an audit as set forth in the Uniform Guidance, 2 C.F.R. Part 200, Subpart F?', 'YESNO', 'ask', 'the Schedule of Expenditures of Federal Awards for 2025, against the Single Audit threshold', 'The 2024 return answered No. This is the one carried answer this record argues with: the organisation holds four America Makes awards and an EDA award, and 2 CFR 200.501 turns on federal expenditure in the year rather than on the prior answer. It is asked rather than carried because carrying it would be the return contradicting the cost record underneath it.'),
  ('P12_3B', 'XII', 690, '3b', 'If Yes, did the organization undergo the required audit or audits?', 'YESNO', 'ask', 'whether the Single Audit was performed, once 3a is answered', ''),
  ('P4_1', 'IV', 700, '1', 'Is the organization described in section 501(c)(3) or 4947(a)(1)? If Yes, complete Schedule A', 'YESNO', 'carried', '', ''),
  ('P4_2', 'IV', 710, '2', 'Is the organization required to complete Schedule B, Schedule of Contributors?', 'YESNO', 'ask', 'whether any contributor gave more than the greater of $5,000 or 2% of line 1h', ''),
  ('P4_3', 'IV', 720, '3', 'Did the organization engage in direct or indirect political campaign activities?', 'YESNO', 'carried', '', ''),
  ('P4_4', 'IV', 730, '4', 'Section 501(c)(3) organizations. Did the organization engage in lobbying activities, or have a section 501(h) election in effect?', 'YESNO', 'carried', '', ''),
  ('P4_5', 'IV', 740, '5', 'Is the organization a section 501(c)(4), 501(c)(5) or 501(c)(6) organization that receives membership dues?', 'YESNO', 'carried', '', ''),
  ('P4_6', 'IV', 750, '6', 'Did the organization maintain any donor advised funds?', 'YESNO', 'carried', '', ''),
  ('P4_7', 'IV', 760, '7', 'Did the organization receive or hold a conservation easement?', 'YESNO', 'carried', '', ''),
  ('P4_8', 'IV', 770, '8', 'Did the organization maintain collections of works of art, historical treasures or other similar assets?', 'YESNO', 'carried', '', ''),
  ('P4_9', 'IV', 780, '9', 'Did the organization report an amount in Part X for escrow or custodial account liability?', 'YESNO', 'carried', '', ''),
  ('P4_10', 'IV', 790, '10', 'Did the organization hold assets in donor-restricted endowments or in quasi endowments?', 'YESNO', 'carried', '', ''),
  ('P4_11A', 'IV', 800, '11a', 'Did the organization report an amount for land, buildings and equipment in Part X, line 10?', 'YESNO', 'record', 'x:X10a', ''),
  ('P4_11B', 'IV', 810, '11b', 'Did the organization report an amount for investments—other securities that is 5% or more of total assets?', 'YESNO', 'record', 'x:X15', ''),
  ('P4_11C', 'IV', 820, '11c', 'Did the organization report an amount for investments—program related that is 5% or more of total assets?', 'YESNO', 'carried', '', ''),
  ('P4_11D', 'IV', 830, '11d', 'Did the organization report an amount for other assets that is 5% or more of total assets?', 'YESNO', 'record', 'x:X15', ''),
  ('P4_11E', 'IV', 840, '11e', 'Did the organization report an amount for other liabilities in Part X, line 25?', 'YESNO', 'record', 'x:X25', ''),
  ('P4_11F', 'IV', 850, '11f', 'Did the organization''s separate or consolidated financial statements include a footnote addressing its liability for uncertain tax positions?', 'YESNO', 'carried', '', ''),
  ('P4_12A', 'IV', 860, '12a', 'Did the organization obtain separate, independent audited financial statements for the tax year?', 'YESNO', 'carried', '', ''),
  ('P4_12B', 'IV', 870, '12b', 'Was the organization included in consolidated, independent audited financial statements for the tax year?', 'YESNO', 'carried', '', ''),
  ('P4_13', 'IV', 880, '13', 'Is the organization a school described in section 170(b)(1)(A)(ii)?', 'YESNO', 'carried', '', ''),
  ('P4_14A', 'IV', 890, '14a', 'Did the organization maintain an office, employees or agents outside of the United States?', 'YESNO', 'carried', '', ''),
  ('P4_14B', 'IV', 900, '14b', 'Did the organization have aggregate revenues or expenses of more than $10,000 from grantmaking, fundraising, business, investment and program service activities outside the United States?', 'YESNO', 'carried', '', ''),
  ('P4_15', 'IV', 910, '15', 'Did the organization report more than $5,000 of grants or other assistance to or for any foreign organization?', 'YESNO', 'record', 'ix:3:total', ''),
  ('P4_16', 'IV', 920, '16', 'Did the organization report more than $5,000 of aggregate grants or other assistance to or for foreign individuals?', 'YESNO', 'carried', '', ''),
  ('P4_17', 'IV', 930, '17', 'Did the organization report more than $15,000 of total fundraising expenses on Part IX, column (A), line 11e?', 'YESNO', 'record', 'ix:11e:total', ''),
  ('P4_18', 'IV', 940, '18', 'Did the organization report more than $15,000 total of fundraising event gross income and contributions on Part VIII, lines 1c and 8a?', 'YESNO', 'record', 'viii:V8', ''),
  ('P4_19', 'IV', 950, '19', 'Did the organization report more than $15,000 of gross income from gaming activities on Part VIII, line 9a?', 'YESNO', 'carried', '', ''),
  ('P4_20A', 'IV', 960, '20a', 'Did the organization operate one or more hospital facilities?', 'YESNO', 'carried', '', ''),
  ('P4_21', 'IV', 970, '21', 'Did the organization report more than $5,000 of grants or other assistance to any domestic organization or domestic government on Part IX, column (A), line 1?', 'YESNO', 'record', 'ix:1:total', ''),
  ('P4_22', 'IV', 980, '22', 'Did the organization report more than $5,000 of grants or other assistance to or for domestic individuals on Part IX, column (A), line 2?', 'YESNO', 'record', 'ix:2:total', ''),
  ('P4_23', 'IV', 990, '23', 'Did the organization answer Yes to Part VII, Section A, line 3, 4 or 5 about compensation?', 'YESNO', 'carried', '', ''),
  ('P4_24A', 'IV', 1000, '24a', 'Did the organization have a tax-exempt bond issue with an outstanding principal amount of more than $100,000?', 'YESNO', 'carried', '', ''),
  ('P4_25A', 'IV', 1010, '25a', 'Did the organization engage in an excess benefit transaction with a disqualified person?', 'YESNO', 'carried', '', ''),
  ('P4_25B', 'IV', 1020, '25b', 'Is the organization aware that it engaged in an excess benefit transaction with a disqualified person in a prior year?', 'YESNO', 'carried', '', ''),
  ('P4_26', 'IV', 1030, '26', 'Did the organization report any amount for receivables from or payables to any current or former officer, director, trustee or key employee?', 'YESNO', 'record', 'x:X7', ''),
  ('P4_27', 'IV', 1040, '27', 'Did the organization provide a grant or other assistance to any current or former officer, director, trustee, key employee or substantial contributor?', 'YESNO', 'carried', '', ''),
  ('P4_28A', 'IV', 1050, '28a', 'Was the organization a party to a business transaction with a current or former officer, director, trustee or key employee?', 'YESNO', 'ask', 'whether any officer or director transacted with the organisation in 2025', ''),
  ('P4_28B', 'IV', 1060, '28b', 'Was the organization a party to a business transaction with a family member of any individual described in line 28a?', 'YESNO', 'carried', '', ''),
  ('P4_28C', 'IV', 1070, '28c', 'Was the organization a party to a business transaction with an entity of which a current or former officer, director, trustee or key employee was an owner or officer?', 'YESNO', 'ask', 'whether an entity an officer or director owns transacted with the organisation', ''),
  ('P4_29', 'IV', 1080, '29', 'Did the organization receive more than $25,000 in non-cash contributions?', 'YESNO', 'carried', '', ''),
  ('P4_30', 'IV', 1090, '30', 'Did the organization receive contributions of art, historical treasures or qualified conservation contributions?', 'YESNO', 'carried', '', ''),
  ('P4_31', 'IV', 1100, '31', 'Did the organization liquidate, terminate or dissolve and cease operations?', 'YESNO', 'carried', '', ''),
  ('P4_32', 'IV', 1110, '32', 'Did the organization sell, exchange, dispose of or transfer more than 25% of its net assets?', 'YESNO', 'carried', '', ''),
  ('P4_33', 'IV', 1120, '33', 'Did the organization own 100% of an entity disregarded as separate from the organization?', 'YESNO', 'carried', '', ''),
  ('P4_34', 'IV', 1130, '34', 'Was the organization related to any tax-exempt or taxable entity?', 'YESNO', 'carried', '', ''),
  ('P4_35A', 'IV', 1140, '35a', 'Did the organization have a controlled entity within the meaning of section 512(b)(13)?', 'YESNO', 'carried', '', ''),
  ('P4_35B', 'IV', 1150, '35b', 'If Yes to line 35a, did the organization receive any payment from or engage in any transaction with a controlled entity?', 'YESNO', 'carried', '', ''),
  ('P4_36', 'IV', 1160, '36', 'Section 501(c)(3) organizations. Did the organization make any transfers to an exempt non-charitable related organization?', 'YESNO', 'carried', '', ''),
  ('P4_37', 'IV', 1170, '37', 'Did the organization conduct more than 5% of its activities through an entity that is treated as a partnership?', 'YESNO', 'carried', '', ''),
  ('P4_38', 'IV', 1180, '38', 'Did the organization complete Schedule O and provide explanations for Part VI, lines 11b and 19?', 'YESNO', 'carried', '', ''),
  ('P5_1A', 'V', 1190, '1a', 'Enter the number reported in box 3 of Form 1096', 'COUNT', 'ask', 'the count of information returns filed for 2025', ''),
  ('P5_1B', 'V', 1200, '1b', 'Enter the number of Forms W-2G included on line 1a', 'COUNT', 'carried', '', ''),
  ('P5_1C', 'V', 1210, '1c', 'Did the organization comply with backup withholding rules for reportable payments to vendors?', 'YESNO', 'carried', '', ''),
  ('P5_2A', 'V', 1220, '2a', 'Enter the number of employees reported on Form W-3 for the calendar year', 'COUNT', 'record', 'fn:employees', ''),
  ('P5_2B', 'V', 1230, '2b', 'If at least one is reported on line 2a, did the organization file all required federal employment tax returns?', 'YESNO', 'carried', '', ''),
  ('P5_3A', 'V', 1240, '3a', 'Did the organization have unrelated business gross income of $1,000 or more during the year?', 'YESNO', 'carried', '', ''),
  ('P5_3B', 'V', 1250, '3b', 'If Yes, has it filed a Form 990-T for this year?', 'YESNO', 'carried', '', ''),
  ('P5_4A', 'V', 1260, '4a', 'Did the organization have an interest in, or signature authority over, a financial account in a foreign country?', 'YESNO', 'carried', '', ''),
  ('P5_5A', 'V', 1270, '5a', 'Was the organization a party to a prohibited tax shelter transaction at any time during the tax year?', 'YESNO', 'carried', '', ''),
  ('P5_5B', 'V', 1280, '5b', 'Did any taxable party notify the organization that it was or is a party to a prohibited tax shelter transaction?', 'YESNO', 'carried', '', ''),
  ('P5_5C', 'V', 1290, '5c', 'If Yes to line 5a or 5b, did the organization file Form 8886-T?', 'YESNO', 'carried', '', ''),
  ('P5_6A', 'V', 1300, '6a', 'Does the organization have annual gross receipts normally greater than $100,000, and did it solicit any contributions that were not tax deductible?', 'YESNO', 'carried', '', ''),
  ('P5_6B', 'V', 1310, '6b', 'If Yes, did the organization include with every solicitation an express statement that such contributions were not tax deductible?', 'YESNO', 'carried', '', ''),
  ('P5_7A', 'V', 1320, '7a', 'Did the organization receive a payment in excess of $75 made partly as a contribution and partly for goods and services?', 'YESNO', 'carried', '', ''),
  ('P5_7B', 'V', 1330, '7b', 'If Yes, did the organization notify the donor of the value of the goods or services provided?', 'YESNO', 'carried', '', ''),
  ('P5_7C', 'V', 1340, '7c', 'Did the organization sell, exchange or otherwise dispose of tangible personal property for which it was required to file Form 8282?', 'YESNO', 'carried', '', ''),
  ('P5_7D', 'V', 1350, '7d', 'If Yes, indicate the number of Forms 8282 filed during the year', 'COUNT', 'carried', '', ''),
  ('P5_7E', 'V', 1360, '7e', 'Did the organization receive any funds, directly or indirectly, to pay premiums on a personal benefit contract?', 'YESNO', 'carried', '', ''),
  ('P5_7F', 'V', 1370, '7f', 'Did the organization pay premiums, directly or indirectly, on a personal benefit contract?', 'YESNO', 'carried', '', ''),
  ('P5_7G', 'V', 1380, '7g', 'If the organization received a contribution of qualified intellectual property, did it file Form 8899?', 'YESNO', 'carried', '', ''),
  ('P5_7H', 'V', 1390, '7h', 'If the organization received a contribution of cars, boats, airplanes or other vehicles, did it file Form 1098-C?', 'YESNO', 'carried', '', ''),
  ('P5_8', 'V', 1400, '8', 'Sponsoring organizations maintaining donor advised funds. Did a donor advised fund have excess business holdings at any time during the year?', 'YESNO', 'carried', '', ''),
  ('P5_9A', 'V', 1410, '9a', 'Did the sponsoring organization make any taxable distributions under section 4966?', 'YESNO', 'carried', '', ''),
  ('P5_9B', 'V', 1420, '9b', 'Did the sponsoring organization make a distribution to a donor, donor advisor or related person?', 'YESNO', 'carried', '', ''),
  ('P5_10A', 'V', 1430, '10a', 'Section 501(c)(7) organizations. Initiation fees and capital contributions included on Part VIII, line 12', 'MONEY', 'carried', '', ''),
  ('P5_10B', 'V', 1440, '10b', 'Section 501(c)(7) organizations. Gross receipts for public use of club facilities', 'MONEY', 'carried', '', ''),
  ('P5_11A', 'V', 1450, '11a', 'Section 501(c)(12) organizations. Gross income from members or shareholders', 'MONEY', 'carried', '', ''),
  ('P5_11B', 'V', 1460, '11b', 'Section 501(c)(12) organizations. Gross income from other sources', 'MONEY', 'carried', '', ''),
  ('P5_12A', 'V', 1470, '12a', 'Section 4947(a)(1) non-exempt charitable trusts. Is the organization filing Form 990 in lieu of Form 1041?', 'YESNO', 'carried', '', ''),
  ('P5_12B', 'V', 1480, '12b', 'If Yes, enter the amount of tax-exempt interest received or accrued during the year', 'MONEY', 'carried', '', ''),
  ('P5_13A', 'V', 1490, '13a', 'Section 501(c)(29) issuers. Is the organization licensed to issue qualified health plans in more than one state?', 'YESNO', 'carried', '', ''),
  ('P5_13B', 'V', 1500, '13b', 'Enter the amount of reserves the organization is required to maintain', 'MONEY', 'carried', '', ''),
  ('P5_13C', 'V', 1510, '13c', 'Enter the amount of reserves on hand', 'MONEY', 'carried', '', ''),
  ('P5_14A', 'V', 1520, '14a', 'Did the organization receive any payments for indoor tanning services during the tax year?', 'YESNO', 'carried', '', ''),
  ('P5_14B', 'V', 1530, '14b', 'If Yes, has it filed a Form 720 to report these payments?', 'YESNO', 'carried', '', ''),
  ('P5_15', 'V', 1540, '15', 'Is the organization subject to the section 4960 tax on payments of more than $1,000,000 in remuneration or excess parachute payments?', 'YESNO', 'record', 'fn:section_4960', ''),
  ('P5_16', 'V', 1550, '16', 'Is the organization an educational institution subject to the section 4968 excise tax on net investment income?', 'YESNO', 'carried', '', ''),
  ('P5_17', 'V', 1560, '17', 'Section 501(c)(21) organizations. Did the trust or any disqualified person engage in activities resulting in an excise tax under section 4951, 4952 or 4953?', 'YESNO', 'carried', '', ''),
  ('P6_1A', 'VI', 1570, '1a', 'Enter the number of voting members of the governing body at the end of the tax year', 'COUNT', 'record', 'fn:voting_members', ''),
  ('P6_1B', 'VI', 1580, '1b', 'Enter the number of voting members included in line 1a who are independent', 'COUNT', 'record', 'fn:independent_members', ''),
  ('P6_2', 'VI', 1590, '2', 'Did any officer, director, trustee or key employee have a family relationship or a business relationship with any other officer, director, trustee or key employee?', 'YESNO', 'carried', '', ''),
  ('P6_3', 'VI', 1600, '3', 'Did the organization delegate control over management duties to a management company or other person?', 'YESNO', 'carried', '', ''),
  ('P6_4', 'VI', 1610, '4', 'Did the organization make any significant changes to its governing documents since the prior Form 990 was filed?', 'YESNO', 'carried', '', ''),
  ('P6_5', 'VI', 1620, '5', 'Did the organization become aware during the year of a significant diversion of the organization''s assets?', 'YESNO', 'carried', '', ''),
  ('P6_6', 'VI', 1630, '6', 'Did the organization have members or stockholders?', 'YESNO', 'carried', '', ''),
  ('P6_7A', 'VI', 1640, '7a', 'Did the organization have members, stockholders or other persons who had the power to elect or appoint members of the governing body?', 'YESNO', 'carried', '', ''),
  ('P6_7B', 'VI', 1650, '7b', 'Are any governance decisions of the organization reserved to persons other than the governing body?', 'YESNO', 'carried', '', ''),
  ('P6_8A', 'VI', 1660, '8a', 'Did the organization contemporaneously document the meetings held or written actions undertaken by the governing body?', 'YESNO', 'carried', '', ''),
  ('P6_8B', 'VI', 1670, '8b', 'Did the organization contemporaneously document the meetings of each committee with authority to act on behalf of the governing body?', 'YESNO', 'carried', '', ''),
  ('P6_9', 'VI', 1680, '9', 'Is there any officer, director, trustee or key employee listed in Part VII, Section A, who cannot be reached at the organization''s mailing address?', 'YESNO', 'carried', '', ''),
  ('P6_10A', 'VI', 1690, '10a', 'Did the organization have local chapters, branches or affiliates?', 'YESNO', 'carried', '', ''),
  ('P6_10B', 'VI', 1700, '10b', 'If Yes, did the organization have written policies governing the activities of such chapters?', 'YESNO', 'carried', '', ''),
  ('P6_11A', 'VI', 1710, '11a', 'Has the organization provided a complete copy of this Form 990 to all members of its governing body before filing the form?', 'YESNO', 'carried', '', ''),
  ('P6_12A', 'VI', 1720, '12a', 'Did the organization have a written conflict of interest policy?', 'YESNO', 'carried', '', ''),
  ('P6_12B', 'VI', 1730, '12b', 'Were officers, directors, trustees and key employees required to disclose annually interests that could give rise to conflicts?', 'YESNO', 'carried', '', ''),
  ('P6_12C', 'VI', 1740, '12c', 'Did the organization regularly and consistently monitor and enforce compliance with the policy?', 'YESNO', 'carried', '', ''),
  ('P6_13', 'VI', 1750, '13', 'Did the organization have a written whistleblower policy?', 'YESNO', 'carried', '', ''),
  ('P6_14', 'VI', 1760, '14', 'Did the organization have a written document retention and destruction policy?', 'YESNO', 'carried', '', ''),
  ('P6_15A', 'VI', 1770, '15a', 'Did the process for determining compensation of the CEO include a review and approval by independent persons, comparability data and contemporaneous substantiation?', 'YESNO', 'carried', '', ''),
  ('P6_15B', 'VI', 1780, '15b', 'Did that process apply to other officers or key employees of the organization?', 'YESNO', 'carried', '', ''),
  ('P6_16A', 'VI', 1790, '16a', 'Did the organization invest in, contribute assets to or participate in a joint venture with a taxable entity during the year?', 'YESNO', 'carried', '', ''),
  ('P6_16B', 'VI', 1800, '16b', 'If Yes, did the organization follow a written policy requiring evaluation of its participation in joint venture arrangements?', 'YESNO', 'carried', '', ''),
  ('P6_17', 'VI', 1810, '17', 'List the states with which a copy of this Form 990 is required to be filed', 'TEXT', 'carried', '', ''),
  ('P6_18', 'VI', 1820, '18', 'Indicate how the organization made its Forms 1023, 990 and 990-T available for public inspection', 'TEXT', 'carried', '', ''),
  ('P6_20', 'VI', 1830, '20', 'State the name, address and telephone number of the person who possesses the organization''s books and records', 'TEXT', 'carried', '', ''),
  ('P7_TABLE', 'VII', 1840, '1a', 'Officers, directors, trustees, key employees and highest compensated employees', 'TEXT', 'record', 'fn:officers', 'The roster carries forward from 2024 on the organisation''s own instruction; the compensation is read from the 2025 payroll register, because a carried roster is not a carried salary.'),
  ('P7_1B', 'VII', 1850, '1b', 'Sub-total of reportable compensation', 'MONEY', 'record', 'fn:officer_pay', ''),
  ('P7_1C', 'VII', 1860, '1c', 'Total from continuation sheets to Part VII, Section A', 'MONEY', 'carried', '', ''),
  ('P7_2', 'VII', 1870, '2', 'Total number of individuals who received more than $100,000 of reportable compensation from the organization', 'COUNT', 'record', 'fn:over_100k', 'The 2024 return answered 3. On the 2025 payroll register it is 4 — the roster carried forward and the register did not, which is the question v_form_990_officer_check was written to ask.'),
  ('P7_B1', 'VII', 1880, 'B 1', 'Independent contractors who received more than $100,000 of compensation', 'TEXT', 'record', 'fn:contractors', 'Every payee the ledger paid more than the threshold the form names — which is not the same list. The form wants compensation for *services*, and a payee alone cannot separate a consultant from an insurer or a utility: the seven below include Medical Mutual of Ohio and Ohio Edison. Naming the gap precisely is more use than a plausible list, and the preparer strikes the ones that are not services.'),
  ('P7_B2', 'VII', 1890, 'B 2', 'Total number of independent contractors who received more than $100,000 of compensation', 'COUNT', 'record', 'fn:contractor_count', ''),
  ('SA_STATUS', 'SCH_A', 1900, 'I 7', 'Reason for public charity status', 'CHECKBOX', 'carried', '', 'An organization that normally receives a substantial part of its support from a governmental unit or from the general public — section 170(b)(1)(A)(vi). Part II is the schedule that follows from it.'),
  ('SA_1', 'SCH_A', 1910, 'II 1', 'Gifts, grants, contributions and membership fees received', 'MONEY', 'field', 'viii:V1', 'The current-year column. The four before it are the prior return''s own, rolled one year on.'),
  ('SA_8', 'SCH_A', 1920, 'II 8', 'Gross income from interest, dividends, rents, royalties and income from similar sources', 'MONEY', 'field', 'add:viii:V3,viii:V6,viii:V5', ''),
  ('SA_9', 'SCH_A', 1930, 'II 9', 'Net income from unrelated business activities', 'MONEY', 'field', 'sub:viii:V8,ix:8b:total', 'The 2024 return put the fundraising event''s net here — 227,890, which is Schedule G Part II line 11 to the dollar. Carried as that definition rather than as the figure.'),
  ('SA_10', 'SCH_A', 1940, 'II 10', 'Other income', 'MONEY', 'field', 'viii:V11', ''),
  ('SA_5', 'SCH_A', 1950, 'II 5', 'The portion of total contributions by each person that exceeds 2% of the amount shown on line 11, column (f)', 'MONEY', 'ask', 'contributions by contributor, which this record does not hold', 'The 2024 return reported 1,491,750. It cannot be derived from a ledger that records grant income by programme rather than by donor.'),
  ('SA_PRIOR', 'SCH_A', 1960, 'II', 'The four prior columns of the support schedule', 'TEXT', 'carried', '', '2021 to 2024 as the 2024 return printed them; 2020 drops off.'),
  ('SA_14', 'SCH_A', 1970, 'II 14', 'Public support percentage for the year', 'PERCENT', 'ask', 'Schedule A Part II line 5, before a percentage can be taken', 'Line 6 is line 4 less line 5, and line 5 is the 2% excess-contributor adjustment nobody can derive from this ledger. Printing a percentage with line 5 assumed at nought would put the organisation''s public charity status on a figure nobody computed.'),
  ('SA_15', 'SCH_A', 1980, 'II 15', 'Public support percentage from the prior year''s Schedule A', 'PERCENT', 'carried', '', ''),
  ('SD_VI', 'SCH_D', 1990, 'VI', 'Land, buildings and equipment', 'MONEY', 'record', 'fn:schedule_d_vi', 'Cost and accumulated depreciation by class, which is Part X line 10 opened up. It reads bs_account, so it cannot disagree with the balance sheet above it.'),
  ('SD_XI', 'SCH_D', 2000, 'XI', 'Reconciliation of revenue per audited financial statements with revenue per return', 'MONEY', 'ask', 'the audited financial statements for 2025, which are not yet issued', ''),
  ('SD_XII', 'SCH_D', 2010, 'XII', 'Reconciliation of expenses per audited financial statements with expenses per return', 'MONEY', 'ask', 'the audited financial statements for 2025, which are not yet issued', ''),
  ('SF_1', 'SCH_F', 2020, 'I', 'Activities per region outside the United States', 'TEXT', 'carried', '', 'Part IV line 14b was answered Yes in 2024 and the schedule carries no region, no expenditure and no grantee. Carried as printed; the preparer settles whether the Yes or the empty schedule is the right one.'),
  ('SG_EVENT', 'SCH_G', 2030, 'II', 'Fundraising event', 'TEXT', 'carried', '', ''),
  ('SG_1', 'SCH_G', 2040, 'II 1', 'Gross receipts', 'MONEY', 'field', 'viii:V8', '2024 reported 367,629 against 2025''s much smaller figure. The two years answer differently whether an event sponsorship is a contribution on line 1 or event income on line 8a, and the difference is on the face of this schedule rather than netted into it.'),
  ('SG_3', 'SCH_G', 2050, 'II 3', 'Gross income (line 1 minus line 2)', 'MONEY', 'field', 'viii:V8', ''),
  ('SG_10', 'SCH_G', 2060, 'II 10', 'Direct expense summary', 'MONEY', 'field', 'ix:8b:total', ''),
  ('SG_11', 'SCH_G', 2070, 'II 11', 'Net income summary', 'MONEY', 'field', 'sub:viii:V8,ix:8b:total', ''),
  ('SG_SPLIT', 'SCH_G', 2080, 'II 4-9', 'Direct expenses by kind — cash prizes, non-cash prizes, rent and facility costs, food and beverages, entertainment, other', 'TEXT', 'ask', 'the event''s direct expenses split by the six kinds the schedule prints', 'The ledger carries the expenses and not the split; the 2024 return reported 50,000 / 14,130 / 39,557 / 7,584 / 28,468.'),
  ('SI_1', 'SCH_I', 2090, 'I 1', 'Does the organization maintain records to substantiate the amount of the grants, the grantees'' eligibility and the selection criteria?', 'YESNO', 'carried', '', ''),
  ('SI_TABLE', 'SCH_I', 2100, 'II', 'Grants and other assistance to domestic organizations and domestic governments', 'TEXT', 'record', 'fn:schedule_i', 'Every payee on Part IX line 1 above the $5,000 the schedule names, read from the ledger. The EIN and IRC section of each grantee are not on this record and print as asked rather than blank.'),
  ('SI_3', 'SCH_I', 2110, 'II 3', 'Enter total number of other organizations listed', 'COUNT', 'record', 'fn:schedule_i_count', ''),
  ('SJ', 'SCH_J', 2120, '', 'Compensation information for certain officers, directors, trustees, key employees and highest compensated employees', 'TEXT', 'record', 'fn:schedule_j', 'Follows Part VII: the people the roster names, with the compensation the register carries.'),
  ('SO', 'SCH_O', 2130, '', 'Supplemental information to Form 990', 'TEXT', 'carried', '', 'Every narrative the 2024 return gave, plus the explanations this return owes for its own asked fields. Schedule O is where a return says what it could not answer, which is the whole of this document''s discipline.');

-- The 2024 filing, as printed. Fields the return left blank carry no
-- row: a blank is unanswered, and unanswered is a value.
INSERT INTO form_990_prior_field (period, field_id, value) VALUES
  ('2024', 'H_PERIOD', '01-01-2024 to 12-31-2024'),
  ('2024', 'H_NAME', 'THE YOUNGSTOWN EDISON BUSINESS INCUBATOR'),
  ('2024', 'H_STREET', '241 FEDERAL PLAZA WEST'),
  ('2024', 'H_CITY', 'YOUNGSTOWN, OH 44503'),
  ('2024', 'H_EIN', '34-1751707'),
  ('2024', 'H_PHONE', '(330) 746-5003'),
  ('2024', 'H_GROSS', '7,685,898'),
  ('2024', 'H_OFFICER', 'JOHN REED, 241 FEDERAL PLAZA WEST, YOUNGSTOWN, OH 44503'),
  ('2024', 'H_STATUS', '501(c)(3)'),
  ('2024', 'H_WEB', 'WWW.YBI.ORG'),
  ('2024', 'H_GROUPA', 'No'),
  ('2024', 'H_FORM', 'Corporation'),
  ('2024', 'H_FORMED', '1988'),
  ('2024', 'H_DOMICILE', 'OH'),
  ('2024', 'P1_1', 'BUSINESS DEVELOPMENT: TO CULTIVATE, ACCELERATE AND PROMOTE THE FORMATION, GROWTH, COMMERCIALIZATION AND INNOVATION OF TECHNOLOGY-BASED BUSINESSES BY PROVIDING COMPREHENSIVE, HIGH QUALITY ENTREPRENEURIAL SERVICES AND RESOURCES IN A ROBUST ENVIRONMENT THAT PROMOTES COMPANY SUCCESS, ATTRACTION AND RETENTION.'),
  ('2024', 'P1_3', '24'),
  ('2024', 'P1_4', '24'),
  ('2024', 'P1_5', '40'),
  ('2024', 'P1_6', '0'),
  ('2024', 'P1_7A', '0'),
  ('2024', 'P1_7B', '0'),
  ('2024', 'P1_8', '6,683,962'),
  ('2024', 'P1_9', '0'),
  ('2024', 'P1_10', '0'),
  ('2024', 'P1_11', '862,197'),
  ('2024', 'P1_12', '7,546,159'),
  ('2024', 'P1_13', '613,545'),
  ('2024', 'P1_14', '0'),
  ('2024', 'P1_15', '1,940,801'),
  ('2024', 'P1_16A', '0'),
  ('2024', 'P1_16B', '238,549'),
  ('2024', 'P1_17', '2,364,655'),
  ('2024', 'P1_18', '4,919,001'),
  ('2024', 'P1_19', '2,627,158'),
  ('2024', 'P1_20', '16,302,782'),
  ('2024', 'P1_21', '1,956,418'),
  ('2024', 'P1_22', '14,346,364'),
  ('2024', 'P2_SIG', 'BARB EWING, CEO, signed 2025-11-06'),
  ('2024', 'P2_PREP', 'MALONEY NOVOTNY LLC, EIN 34-0677006, 1111 SUPERIOR AVE SUITE 700, CLEVELAND, OH 441142540, (216) 363-0100, PTIN P00226559'),
  ('2024', 'P2_DISCUSS', 'Yes'),
  ('2024', 'P3_1', 'BUSINESS DEVELOPMENT: TO CULTIVATE, ACCELERATE AND PROMOTE THE FORMATION, GROWTH, COMMERCIALIZATION AND INNOVATION OF TECHNOLOGY-BASED BUSINESSES BY PROVIDING COMPREHENSIVE, HIGH QUALITY ENTREPRENEURIAL SERVICES AND RESOURCES IN A ROBUST ENVIRONMENT THAT PROMOTES COMPANY SUCCESS, ATTRACTION AND RETENTION.'),
  ('2024', 'P3_2', 'No'),
  ('2024', 'P3_3', 'No'),
  ('2024', 'P3_4A_EXP', '4,119,113'),
  ('2024', 'P3_4A_GRANT', '613,545'),
  ('2024', 'P3_4A_REV', '634,307'),
  ('2024', 'P3_4A_DESC', 'TO ACCELERATE THE FORMATION OF BUSINESS, CREATION OF JOBS AND ASSIST IN THE REVITALIZATION AND GROWTH OF THE MAHONING VALLEY.'),
  ('2024', 'P3_4E', '4,119,113'),
  ('2024', 'P11_1', '7,546,159'),
  ('2024', 'P11_2', '4,919,001'),
  ('2024', 'P11_3', '2,627,158'),
  ('2024', 'P11_4', '11,769,206'),
  ('2024', 'P11_9', '-50,000'),
  ('2024', 'P11_10', '14,346,364'),
  ('2024', 'P12_1', 'Accrual'),
  ('2024', 'P12_2A', 'No'),
  ('2024', 'P12_2B', 'Yes'),
  ('2024', 'P12_2C', 'Yes'),
  ('2024', 'P12_3A', 'No'),
  ('2024', 'P4_1', 'Yes'),
  ('2024', 'P4_2', 'No'),
  ('2024', 'P4_3', 'No'),
  ('2024', 'P4_4', 'No'),
  ('2024', 'P4_5', 'No'),
  ('2024', 'P4_6', 'No'),
  ('2024', 'P4_7', 'No'),
  ('2024', 'P4_8', 'No'),
  ('2024', 'P4_9', 'No'),
  ('2024', 'P4_10', 'No'),
  ('2024', 'P4_11A', 'Yes'),
  ('2024', 'P4_11B', 'No'),
  ('2024', 'P4_11C', 'No'),
  ('2024', 'P4_11D', 'No'),
  ('2024', 'P4_11E', 'No'),
  ('2024', 'P4_11F', 'No'),
  ('2024', 'P4_12A', 'Yes'),
  ('2024', 'P4_12B', 'No'),
  ('2024', 'P4_13', 'No'),
  ('2024', 'P4_14A', 'No'),
  ('2024', 'P4_14B', 'Yes'),
  ('2024', 'P4_15', 'No'),
  ('2024', 'P4_16', 'No'),
  ('2024', 'P4_17', 'No'),
  ('2024', 'P4_18', 'Yes'),
  ('2024', 'P4_19', 'No'),
  ('2024', 'P4_20A', 'No'),
  ('2024', 'P4_21', 'Yes'),
  ('2024', 'P4_22', 'No'),
  ('2024', 'P4_23', 'Yes'),
  ('2024', 'P4_24A', 'No'),
  ('2024', 'P4_25A', 'No'),
  ('2024', 'P4_25B', 'No'),
  ('2024', 'P4_26', 'No'),
  ('2024', 'P4_27', 'No'),
  ('2024', 'P4_28A', 'No'),
  ('2024', 'P4_28B', 'No'),
  ('2024', 'P4_28C', 'No'),
  ('2024', 'P4_29', 'No'),
  ('2024', 'P4_30', 'No'),
  ('2024', 'P4_31', 'No'),
  ('2024', 'P4_32', 'No'),
  ('2024', 'P4_33', 'No'),
  ('2024', 'P4_34', 'No'),
  ('2024', 'P4_35A', 'No'),
  ('2024', 'P4_36', 'No'),
  ('2024', 'P4_37', 'No'),
  ('2024', 'P4_38', 'Yes'),
  ('2024', 'P5_1A', '73'),
  ('2024', 'P5_1B', '0'),
  ('2024', 'P5_1C', 'Yes'),
  ('2024', 'P5_2A', '40'),
  ('2024', 'P5_2B', 'Yes'),
  ('2024', 'P5_3A', 'No'),
  ('2024', 'P5_4A', 'No'),
  ('2024', 'P5_5A', 'No'),
  ('2024', 'P5_5B', 'No'),
  ('2024', 'P5_6A', 'No'),
  ('2024', 'P5_7A', 'No'),
  ('2024', 'P5_7C', 'No'),
  ('2024', 'P5_7E', 'No'),
  ('2024', 'P5_7F', 'No'),
  ('2024', 'P5_14A', 'No'),
  ('2024', 'P5_15', 'No'),
  ('2024', 'P5_16', 'No'),
  ('2024', 'P6_1A', '24'),
  ('2024', 'P6_1B', '24'),
  ('2024', 'P6_2', 'No'),
  ('2024', 'P6_3', 'No'),
  ('2024', 'P6_4', 'No'),
  ('2024', 'P6_5', 'No'),
  ('2024', 'P6_6', 'No'),
  ('2024', 'P6_7A', 'No'),
  ('2024', 'P6_7B', 'No'),
  ('2024', 'P6_8A', 'Yes'),
  ('2024', 'P6_8B', 'Yes'),
  ('2024', 'P6_9', 'No'),
  ('2024', 'P6_10A', 'No'),
  ('2024', 'P6_11A', 'No'),
  ('2024', 'P6_12A', 'Yes'),
  ('2024', 'P6_12B', 'Yes'),
  ('2024', 'P6_12C', 'Yes'),
  ('2024', 'P6_13', 'No'),
  ('2024', 'P6_14', 'No'),
  ('2024', 'P6_15A', 'Yes'),
  ('2024', 'P6_15B', 'No'),
  ('2024', 'P6_16A', 'No'),
  ('2024', 'P6_17', 'OH'),
  ('2024', 'P6_18', 'Upon request'),
  ('2024', 'P6_20', 'TOM METZINGER, 241 FEDERAL PLAZA WEST, YOUNGSTOWN, OH 44503, (330) 746-5003'),
  ('2024', 'P7_TABLE', '27 persons listed'),
  ('2024', 'P7_1B', '233,693'),
  ('2024', 'P7_2', '3'),
  ('2024', 'SA_STATUS', '170(b)(1)(A)(vi) — Part II completed'),
  ('2024', 'SA_1', '6,683,962'),
  ('2024', 'SA_8', '616,045'),
  ('2024', 'SA_9', '227,890'),
  ('2024', 'SA_10', '18,262'),
  ('2024', 'SA_5', '1,491,750'),
  ('2024', 'SA_PRIOR', '2020 2,654,022 · 2021 2,905,073 · 2022 3,496,419 · 2023 3,320,829 · 2024 6,683,962'),
  ('2024', 'SA_14', '78.180 %'),
  ('2024', 'SA_15', '78.180 %'),
  ('2024', 'SD_VI', 'Cost 22,393,574 · A/D 8,730,051 · Net 13,663,523'),
  ('2024', 'SD_XI', 'Not completed on the 2024 return'),
  ('2024', 'SD_XII', 'Not completed on the 2024 return'),
  ('2024', 'SF_1', 'Answered Yes on Part IV line 14b; no region, expenditure or grantee listed'),
  ('2024', 'SG_EVENT', 'SHARK TANK'),
  ('2024', 'SG_1', '367,629'),
  ('2024', 'SG_3', '367,629'),
  ('2024', 'SG_10', '139,739'),
  ('2024', 'SG_11', '227,890'),
  ('2024', 'SG_SPLIT', '50,000 cash prizes · 14,130 rent · 39,557 food · 7,584 entertainment · 28,468 other'),
  ('2024', 'SI_1', 'Yes'),
  ('2024', 'SI_TABLE', '22 organizations listed'),
  ('2024', 'SI_3', '22'),
  ('2024', 'SJ', 'Completed for the persons listed on Part VII'),
  ('2024', 'SO', 'Narratives for Part VI line 11b and line 19, and Schedule A Part II line 10');
